[libraries]
# Kotlin
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common" }
kotlin-test-annotations-common = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.3.2" }

[plugins]
kotlin-multiplaform = { id = "org.jetbrains.kotlin.multiplatform", version = "1.6.21" }
kotlinx-binary-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.10.0" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.19.0" }
spotless = { id = "com.diffplug.gradle.spotless", version = "6.6.1" }
